# agents/jira_notifier.py

import requests
import os
import json

JIRA_BASE_URL = os.getenv("JIRA_BASE_URL")       # e.g. https://yourcompany.atlassian.net
JIRA_EMAIL = os.getenv("JIRA_EMAIL")
JIRA_API_TOKEN = os.getenv("JIRA_API_TOKEN")
JIRA_PROJECT_KEY = os.getenv("JIRA_PROJECT_KEY") # e.g. "AIPM"

def create_feature_ticket(pain_theme: dict) -> dict:
    """
    Auto-creates a Jira ticket from a Synthesis Agent pain theme.
    pain_theme format: {"theme": str, "severity": float, "frequency": int, "opportunity": str}
    """
    if not all([JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN, JIRA_PROJECT_KEY]):
        print(f"[Jira - DRY RUN] Would create ticket for: {pain_theme.get('theme', 'unknown')}")
        return {"status": "dry_run", "theme": pain_theme.get("theme")}

    url = f"{JIRA_BASE_URL}/rest/api/3/issue"
    auth = (JIRA_EMAIL, JIRA_API_TOKEN)
    headers = {"Content-Type": "application/json"}

    payload = {
        "fields": {
            "project": {"key": JIRA_PROJECT_KEY},
            "summary": f"[AI Loop] {pain_theme.get('theme', 'User Pain Theme')}",
            "description": {
                "type": "doc", "version": 1,
                "content": [{
                    "type": "paragraph",
                    "content": [{"type": "text", "text": 
                        f"Opportunity: {pain_theme.get('opportunity', 'N/A')}\n"
                        f"Severity score: {pain_theme.get('severity', 'N/A')}\n"
                        f"Frequency: {pain_theme.get('frequency', 'N/A')}\n"
                        f"Auto-generated by AI Product Intelligence Loop — Synthesis Agent."
                    }]
                }]
            },
            "issuetype": {"name": "Story"},
            "priority": {"name": "High" if pain_theme.get("severity", 0) > 0.7 else "Medium"}
        }
    }

    response = requests.post(url, auth=auth, headers=headers, json=payload)
    return {"status": response.status_code, "key": response.json().get("key", "error")}